import type { Metadata } from "next";
import { Playfair } from "next/font/google";
import "./globals.css";

const playfairSans = Playfair();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body
        className={`${playfairSans.className}  antialiased p-15 bg-[#FFF4E6]`}
      >
        <div className="max-w-[1440px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
